// from https://www.intel.com/content/dam/develop/public/us/en/documents/sgx-attestation-api-spec.pdf

/// Attestation Evidence Payload is a data structure submitted by the Service Provider to IAS so that 
/// identity of the ISV enclave and the validity of the platform can be verified.
struct EvidencePayload {
    /// Base 64-encoded QUOTE structure generated by QE for the ISV 
    /// enclave. See Quoting Data Structures for details
    ///
    /// This field is mandatory.
    isvEnclaveQuote: String,
    /// Base 64-encoded SGX Platform Service Security Property Descriptor structure provided by the platform. 
    ///
    /// This field is optional, it will be present only if ISV enclave uses SGX Platform Service. 
    pseManifest: String,
    /// A string that represents custom nonce value provided by SP. Maximum size of the nonce is 32 characters. 
    /// 
    /// This field is optional
    /// If this field is present, it will be returned back to SP as part of Attestation Verification Report.
    nonce: String,
}

struct ReportData {
    /// Representation of unique identifier of the Attestation Verification Report.
    /// 
    /// This field is mandatory. 
    id: String,
    ///
    timestamp: String,
    version: Number,
    isvEnclaveQuoteStatus: String,
    isvEnclaveQuoteBody: String,
    revocationReason: Number,
    pseManifestStatus: String,
    pseManifestHash: String,
    platformInfoBlob: String,
    nonce: String,
    epidPseudonym: String,
    advisoryURL: String,
    advisoryIDs: Vec<String>,
}

